version: "3.9"

services:
  tg-parser:
    build: .
    container_name: tg-parser
    restart: always
    environment:
      API_ID: "24376250"
      API_HASH: "2a470c2c5891f05f67ab97c9437ca6a7"
      SOURCE_CHAT: "-1001487687256"
      TARGET_CHAT: "-1003641327064"
    volumes:
      - ./session.session:/app/session.session

